# Generated by Django 3.1.7 on 2022-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/'),
        ),
    ]
